name: async_task
description: Asynchronous tasks and parallel executors (similar to thread pools) for all Dart platforms (transparently), without having to deal with `Isolate` complexity.
version: 1.0.18
homepage: https://github.com/eneural-net/async_task

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  async_extension: ^1.0.9
  ffi: ^1.1.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.5
  dependency_validator: ^3.1.2
  coverage: ^1.0.3
  vm_service: ^8.1.0
